# Generated by Django 4.1.3 on 2023-06-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Pieza',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=12)),
                ('fecha_compra', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('orden_trabajo', models.CharField(max_length=20)),
                ('precio_tienda', models.FloatField()),
                ('import_fact', models.FloatField()),
                ('pre_fact', models.CharField(default='-', max_length=20)),
                ('fact', models.CharField(default='-', max_length=20)),
                ('entregado', models.CharField(max_length=50)),
                ('recibe', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.municipio')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.pieza')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.tipo_venta')),
            ],
        ),
    ]
